### ISSUE TITLE
feat(comp.ui): Implement Instance Count per Component

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#102]
Enabling total number of instances per component in the UI.

**Comment by TilmanHaupt** [comment]
After discussions we decided that the total number of errors of all components of all versions are not useful. The number of running instances took the place

**Comment by TilmanHaupt** [comment]
implemented in: https://github.com/cloudoperators/greenhouse-extensions/pull/314/

**Comment by TilmanHaupt** [comment]
implemented in: https://github.com/cloudoperators/greenhouse-extensions/pull/314
