### ISSUE TITLE
feat(comp.backend): Enable filtering for component instance without support group or service

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#180]
**Task Description**
We need to have a design session to decide the following:
- how to identify non-values
- the pattern for non-existing - we can consider naming the list of component instances in this category (no service, no support group)

**Acceptance Criteria:**
- [ ] ADR is discussed and there is a agreement to a solution
- [ ] Filtering option is implemented according to the ADR

**Expected Test:**
Database-Layer, APP-Layer and E2E Test.

**Comment by MR2011** [comment]
Having no service is not possible in the database:
https://github.com/cloudoperators/heureka/blob/main/internal/database/mariadb/init/schema.sql#L105

**Comment by lolaapenna** [comment]
Create an ADR considering the options.

**Comment by lolaapenna** [comment]
@dustindemmerle, could you kindly fill in the issue's **Acceptance criteria** and **Expected Test** sections?

**Comment by dustindemmerle** [comment]
ADR for Identification of Component Instances without support group or service:
https://codi.eu-nl-1.cloud.sap/DAyEAcAqQIS765JZyw0lYw?view

**Comment by lolaapenna** [comment]
Decision has been made, we just need to update the ADR.
