### ISSUE TITLE
feat(ui): Add CCRN to issue matches list

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#185]
**Task Description**
We need to include CCRN (Common Cloud Resource Names) details to the issue matches.

**Acceptance Criteria:**
- [ ] AC 1

**Expected Test:**

**Comment by hodanoori** [comment]
It could not be done before having real data including CCRN in the apiEndpoint.
Therefore, it should be shipped into next sprint(10/24).
