### ISSUE TITLE
epic(matches): Heureka Issue Matches

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#27]
This entails the automated discovery of existing security issues based on the results of the issue scanners. Issues and the component instances they impact are matched.

Acceptance Criteria
- Leverage component discovery information to match identified security issues with the specific components or component instances they impact.
- The matching process should consider various factors (vulnerable versions, associated CVEs, etc) to ensure accurate association between issues and component instances.
- The UI shall display security issues with clear associations to impacted components and their instances thereby allowing informed decision making such as prioritisation and remediation efforts.

Tasks:

- [ ] #167
- [x] #168 
- [x] #169 
- [x] #170
- [x] #188

**Comment by dorneanu** [comment]
Marked #188 as done.
