### ISSUE TITLE
fix(issue): Issue List View Aggregation Query

### ISSUE THREAD

**Issue by MR2011** [cloudoperators/heureka#278]
Task Description

For performance reasons an aggregation of the several counts is required. Review the existing aggregations whether they work or not and if the performance can be improved

Acceptance Criteria:

- [ ] Count activities
- [ ] Count issue matches
- [ ] Count AffectedServices
- [ ] Count ComponentVersions

Expected Test:

    Test aggregations in the respective layers

**Comment by lolaapenna** [comment]
Moving to next sprint
