### ISSUE TITLE
feat(authN): Implement Token based Authentication

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#83]

**Comment by drochow** [comment]
To enable Authentication to the API for Scanners (technical Users) please implement a Token based authentication. 
The Token should always be time constrained and stored in the Database as a salted SHA-384 hash.

**Comment by drochow** [comment]
The Token should be stored in a new Table / Entity that is referenced to the user. A user can have multiple active tokens. 

For Tokens we want an real deletion and not just an soft delete as on all other models. 

Please implement as well all tests.

**Comment by lolaapenna** [comment]
We need to implement testing.

**Comment by lolaapenna** [comment]
Working on test refactoring now.
